DELETE http://localhost:3001/api/persons/1
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mohamed Esam",
  "number": "010-12345678"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "010-12345678"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mohamed Esam"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "010-12345678"
}